-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgsHwtUEjd+MR3MIOt
orNQDrbzKkEgQe1NuBN3kjuMP2KgCgYIKoZIzj0DAQehRANCAAQ8oByzJuvsytLa
jiROpiUDW2m0Xln5JxSNgJH4p3QAz9GAn9oaFs9UH8AIooJIxn6Kq/PUygDxoby6
Ars47Mx/
-----END PRIVATE KEY-----