version: "3"
services:
  postgis:
    image: kartoza/postgis:11.0-2.5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=kylekendall
      - POSTGRES_PASS=password
      - POSTGRES_DBNAME=carswaddle
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology # You can pass as many extensions as you need.