version: '3.7'

services:
    carswaddle:
        build:
            context: .
            dockerfile: ./docker/app/Dockerfile
        restart: unless-stopped
        ports:
            - '3000:3000'
            - '9229:9229'
        depends_on:
            - db
            - s3
        networks:
            - carswaddle-net

    db:
        image: kartoza/postgis:12.0
        restart: always
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=kylekendall
            - POSTGRES_PASS=password
            - POSTGRES_DBNAME=carswaddle
            - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology
            - ALLOW_IP_RANGE=0.0.0.0/0
        volumes:
            - postgres-data:/var/lib/postgresql
        networks:
            - carswaddle-net
    
    s3:
        image: minio/minio:latest
        restart: always
        ports:
            - '9000:9000'
        volumes:
            - s3:/data
        environment:
            MINIO_ACCESS_KEY: minio
            MINIO_SECRET_KEY: minio123
        command: server /data
        networks:
            - carswaddle-net
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
            interval: 30s
            timeout: 20s
            retries: 3

volumes:
    postgres-data:
    s3:

networks:
    carswaddle-net:
        driver: bridge
